SELECT * FROM starbucks_analytics_db.sales;

 -- What is the total revenue generated by Starbucks Limited?
	SELECT sum(total_amount) as total_revenue		FROM Sales;
        
 -- Question 2 : How many transactions have been completed?
		  SELECT  count(distinct transaction_id) as unique_transaction			FROM Sales;
            
            -- Question 3 How many unique customers have made purchases?
            		  SELECT  count(distinct customer_id) as customer_with_purchase		FROM Sales;
                      
			-- Which 10 products generated the highest revenue?
				select item_id,  sum(total_amount) as total_revenue	
				FROM Sales
				GROUP BY item_id
				order by total_revenue desc
				limit 10 ;
                          -- Which 10 products sold the highest quantity?
            select item_id,  sum(quantity) as total_quantity	
				FROM Sales 
        		GROUP BY item_id
                order by total_quantity desc
                limit 10;
                
-- Question 6 (INNER JOIN), Display: • Customer Name • Product Name • Quantity Purchased • Revenue Generated Use the appropriate JOIN --.
 
 SELECT C.customer_name, I.item, sum(S.quantity) as Quantity_purchased, sum(S.Total_amount) as Revenue
 FROM sales s
 inner join item I on s.item_id = I.item_id
 inner join customers C on s.customer_id = c.customer_id
 group by  C.customer_name, I.item
 ;
-- Question 7 (INNER JOIN + AGGREGATION) Show: • Customer Name • Total Orders • Total Revenue Sort from highest to lowest revenue.
SELECT C.customer_name, COUNT(distinct S.Transaction_id) as Total_order, SUM(S.Total_amount) as Revenue
FROM Sales S 
INNER JOIN Customers C on s.customer_id = c.customer_id
group by c.customer_name -- (having total_order >= 20 to filter orders > 20)
order by revenue desc;
				
		-- Question 8 (INNER JOIN + AGGREGATION) Show: • Product Name • Total Quantity Sold • Total Revenue Sort by revenue
        SELECT I.Item, SUM(S.Quantity) as Total_Quantity_Sold, SUM(S.total_amount) as Revenue
        FROM Sales S
        INNER JOIN Item I ON S.item_id = I.Item_id
        GROUP BY I.Item
        ORDER BY Revenue;
        
        -- Question 9 Identify products that have never been sold. Management wants to know which products are occupying inventory without generating revenue
        SELECT i.item, i.item_id
        FROM Item I 
        LEFT JOIN sales S ON S.Item_id = I.Item_id
        where s.item_id IS null;
        
-- Question 10Identify customers who have never made a purchase.
    SELECT C.Customer_name, C.customer_id
    FROM Customers C 
    left join Sales S ON S.CUSTOMER_id = C.customer_id
    where s.transaction_id is null;
    
    -- Which month generated the highest revenue?
    SELECT 
    date_format(datetime, '%m') As Month,
    Sum(total_amount) as revenue
    FROM Sales 
    group by date_format(datetime, '%m')
    order by revenue desc
    limit 1;
    
-- Which month generated the lowest revenue?
 SELECT 
    date_format(datetime, '%m') As Month,
    Sum(total_amount) as revenue
    FROM Sales 
    group by date_format(datetime, '%m')
    order by revenue asc
    limit 1;
    
    -- Calculate Average Order Value.
    SELECT Sum(total_amount)/count(distinct transaction_id) as Avg_Order_Value
    FROM Sales;
    
    -- Identify the top 5 customers contributing the most revenue.
    SELECT C.customer_name, c.customer_id,
    sum(s.total_amount) as revenue
    from sales s
    join customers c on c.customer_id = s.customer_id
    group by C.customer_name, c.customer_id
    order by revenue desc
    limit 5;
    
-- Show monthly sales trends. Expected Output: • Month • Revenue • Quantity Sold • Number of Transaction
select
date_format(datetime, '%m') as Month,
sum(total_amount) as Revenue,
sum(quantity) as Quantity_sold,
count(distinct transaction_id) as No_Of_Transaction
from sales
group by month;
						SELECT i.*, S.*
							FROM Item I 
								LEFT JOIN sales S ON S.Item_id = I.Item_id;